version: '3.7'

services:
  database:
    image: postgres

    restart: always

    ports:
      - 5432:5432

    networks:
      - app

    volumes:
      - .:/usr/app

    environment:
      - POSTGRES_USER=value
      - POSTGRES_PASSWORD=value
      - POSTGRES_DB=value


  app:
    container_name: value

    build: .

    restart: always

    depends_on:
      - database

    ports:
      - 3333:3333

    networks:
    - app

networks:
  app:
